#!/usr/bin/python3
matrix_divided = __import__('2-matrix_divided').matrix_divided

matrix = [
    [8, 9, 2],
   [4, 5, 6],
   [0]
]
try:
    print(matrix_divided(None, 3))
    print(matrix)
except TypeError as e:
    print(e)
